config/routes.rb
Rails.application.routes.draw do
  get 'followers/index'
  get 'homes/show'
  constraints Clearance::Constraints::SignedIn.new do
    root 'dashboards#show'
  end

  root 'homes#show'
  resources :shouts, only: [:create, :show] do
    member do
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
    end
  end

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, only: [:create, :show] do
    resources :followers, only: [:index]
    member do
      post 'follow', to: 'followed_users#create'
      delete 'unfollow', to: 'followed_users#destroy'
    end
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/followship.rb
class Followship < ApplicationRecord
  belongs_to :followed_user, class_name: 'User', counter_cache: :followers_count
  belongs_to :follower, class_name: 'User', counter_cache: :followed_users_count
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :shout

  validates :user_id, uniqueness: { scope: :shout_id }
end

app/models/photo_shout.rb
class PhotoShout < ApplicationRecord
  has_attached_file :image, styles: { thumb: '200x200' }
  
  validates_attachment :image, 
    content_type: { content_type: ['image/jpeg', 'image/png', 'image/gif'] },
    size: { in: 0..10.megabytes },
    presence: true
end

app/models/shout.rb
class Shout < ApplicationRecord
  # Includes
  
  # Associations
  belongs_to :user
  belongs_to :content, polymorphic: true
  
  # Validations
  validates :user, presence: true
  
  # Delegations
  delegate :username, to: :user
  
  # Callbacks

  # Scopes
  default_scope { order(created_at: :desc) }
  
  # Class Methods

  # Instance Methods

  # Private Methods
  
end

app/models/text_shout.rb
class TextShout < ApplicationRecord
  # Validations
  validates :body, presence: true, length: { in: 1..144 }

end

app/models/user.rb
class User < ApplicationRecord
  # Includes
  include Clearance::User

  # Associations
  has_many :shouts, dependent: :destroy
  has_many :likes
  has_many :liked_shouts, through: :likes, source: :shout
  
  has_many :followships, foreign_key: :follower_id
  has_many :followed_users, through: :followships
  
  has_many :followerships, 
    foreign_key: :followed_user_id,
    class_name: 'Followship',
    dependent: :destroy
  has_many :followers, through: :followerships

  # Validations
  validates :username, presence: true, uniqueness: true

  
  # Delegations
  
  # Callbacks
  
  # Scopes
  default_scope { order(created_at: :desc) }
  
  # Class Methods

  # Instance Methods
  def follow(user)
    followed_users << user
  end

  def unfollow(user)
    followed_users.destroy(user)
  end

  def following?(user)
    followed_user_ids.include?user.id
  end

  def like(shout)
    liked_shouts << shout
  end

  def dislike(shout)
    liked_shouts.destroy(shout)
  end

  def liked?(shout)
    liked_shout_ids.include?shout.id
  end
  
  def newsfeed_shouts
    Shout.where(user_id: followed_user_ids)
  end

  # Private Methods
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  
  include Clearance::Controller
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @shout = Shout.new
    @shouts = current_user.newsfeed_shouts
  end
end

app/controllers/followed_users_controller.rb
class FollowedUsersController < ApplicationController
  
  def create 
    user_to_follow = find_user
    current_user.follow(user_to_follow)
    redirect_to user_to_follow
  end

  def destroy
    user_to_unfollow = find_user
    current_user.unfollow(user_to_unfollow)
    redirect_to user_to_unfollow
  end

  private

  def find_user
    @_user ||= User.find(params[:id])
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  def index
    @user = find_user
    @followers = @user.followers
  end

  private 

  def find_user
    @_user ||= User.find(params[:user_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
  def create
    current_user.like(shout)
    redirect_back(fallback_location: root_path)
  end

  def destroy
    current_user.dislike(shout)
    redirect_back(fallback_location: root_path)
  end

  private

  def shout
    @_shout ||= Shout.find(params[:id])
  end

end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
  def show
    @shout = Shout.find(params[:id])
  end

  def create
    shout = current_user.shouts.create shouts_params
    redirect_to root_path, redirect_options_for(shout)
  end

  private

  def shouts_params
    { content: new_content_shout }
  end

  def new_content_shout
    case params[:shout][:content_type]
      when 'TextShout' then TextShout.new(text_shout_content_params)
      when 'PhotoShout' then PhotoShout.new(photo_shout_content_paramas)
    end
  end

  def text_shout_content_params
    params.require(:shout).require(:content).permit(:body)
  end

  def photo_shout_content_paramas
    params.require(:shout).require(:content).permit(:image)
  end

  def redirect_options_for(shout)
    if shout.persisted?
      { notice: 'Shout published' }
    else
      { alert: 'Could not shout' }
    end
  end

end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @shouts = @user.shouts
  end
  
  private 
  
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followed_users_helper.rb
module FollowedUsersHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/shout_helper.rb
module ShoutHelper
  
  def avatar(user)
    email_digest = Digest::MD5::hexdigest(user.email)
    gravatar_url = "//www.gravatar.com/avatar/#{email_digest}"
    image_tag gravatar_url, class: 'profile-image'
  end

  def like_button(shout)
    if current_user.liked?(shout)
      link_to image_tag('dislike.png'), unlike_shout_path(shout), method: :delete, class: 'like-btn'
    else
      link_to image_tag('like.png'), like_shout_path(shout), method: :post, class: 'like-btn'
    end
  end

  def likes_counter(shout)
    Like.where(shout_id: shout.id).count
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def follow_button(user)
    if current_user.following?(user)
      button_to 'Unfollow', unfollow_user_path(user), method: :delete
    else
      button_to 'Follow', follow_user_path(user)
    end
  end
end

app/views/application/_footer.html.erb
<footer class="footer">
  <h1>© <%= Date.today.year %> Shoutr</h1>
  <ul class="footer-nav-links">
    <li><%= link_to "Terms", root_path %></li>|
    <li><%= link_to "Privacy", root_path %></li>
  </ul>
</footer>

app/views/application/_header.html.erb
<header>

  <ul class="header-nav-links">
    <% if signed_in? %>
      <li><%= link_to current_user.username, current_user %></li>
      <li><%= link_to 'Sign out', sign_out_path, method: :delete %></li>
    <% else %>
      <li><%= link_to 'Sign In', sign_in_path %></li>
      <li><%= link_to 'Sign Up', sign_up_path %></li>
    <% end %>
  </ul>
  
</header>

app/views/followers/index.html.erb
<h1>
  <%= @user.username %>'s followers
</h1>

<%= render @followers %>

app/views/homes/show.html.erb
<h1>This is landing page</h1>

app/views/shouts/_shout.html.erb
<div class="shout">
  <div class="avatar">
    <%= avatar(shout.user) %>
  </div>

  <p class="shout-author">
    <%= link_to shout.username, shout.user %>
  </p>

  <p class="shout-body">
    <%= render shout.content %>
  </p>

  <p class="shout-creation-time">
    <%= link_to shout do %>
      <%= time_ago_in_words(shout.created_at) %> ago
    <% end %>
  </p>


  <div class="likesbox">
    <%= likes_counter(shout) %>
    <%= like_button(shout) %>
  </div>

</div>

app/views/shouts/show.html.erb
<%= render @shout %>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :username %><br>
  <%= form.text_field :username %>
</div>

<div class="text-field">
  <%= form.label :email %><br>
  <%= form.email_field :email %>
</div>

<div class="password-field">
  <%= form.label :password %><br>
  <%= form.password_field :password %>
</div>

app/views/users/_user.html.erb
<%= link_to user.username, user %>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user-profile">
  <%= avatar @user %>
  <h3><%= @user.username %></h3>
  <%= follow_button @user %>
  <div class="followship-counter">
    <small>
      <%#= link_to 'Following', user_followings_path(@user) %>
      Following: 
      <%= @user.followed_users_count %>
    </small>
    <small>
      <%= link_to 'Followers', user_followers_path(@user) %>
      <%= @user.followers_count %>
    </small>
  </div>
</div>

<%= render @shouts %>